import type { NextPage } from "next"
import Head from "next/head"
import Landing from "src/components/sections/landing"

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>GitHub | Searching</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Landing />
        </>
    )
}

export default Home
