import type { NextPage } from "next"
import Head from "next/head"
import RepositoriesScreen from "src/components/sections/repositories"

const Repositories: NextPage = () => {
    return (
        <>
            <Head>
                <title>Usuarios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RepositoriesScreen />
        </>
    )
}

export default Repositories
