import type { NextPage } from "next"
import Head from "next/head"
import UsersScreen from "src/components/sections/users"

const Users: NextPage = () => {
    return (
        <>
            <Head>
                <title>Usuarios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <UsersScreen />
        </>
    )
}

export default Users
